const express= require("express")
const index = require("../controller")
const category = require("../controller/admin/category")
const user = require("../controller/admin/user")
const cart = require("../controller/cart")
const comment = require("../controller/comment")
const get_category = require("../controller/get_category")
const get_detail_book = require("../controller/get_detail_book")
const get_most_popular_book = require("../controller/get_most_popular_book")
const get_release_book = require("../controller/get_release_book")
const get_history = require("../controller/history")
const login = require("../controller/login")
const search = require("../controller/search")
const signup = require("../controller/signup")
const update_user = require("../controller/update_user")
const router= express.Router()

router.post("/api/signup", signup)
router.post("/api/login", login)
router.post("/api/", index)
router.get("/api/get_release_book", get_release_book)
router.get("/api/book", get_detail_book)
router.get("/api/cart", cart.get)
router.post("/api/cart/add", cart.add)
router.post("/api/cart/delete", cart.delete)
router.post("/api/user/update", update_user)
router.get("/api/search", search)
router.get("/api/comment", comment.get)
router.post("/api/comment/add", comment.add)
router.get("/api/get_most_popular_book", get_most_popular_book)
router.get("/api/get_category", get_category)
router.get("/api/v3/user", user.get)
router.post("/api/v3/category/add", category.add)
router.post("/api/v3/category/update", category.update)
router.post("/api/v3/category/delete", category.delete)
router.get("/api/history", get_history)

module.exports= router